services:
  - type: web
    name: gymapp
    env: dotnet
    plan: free
    buildCommand: dotnet publish GymApp/GymApp.csproj -c Release -o out
    startCommand: dotnet out/GymApp.dll
    repo: https://github.com/GitMaksi/GymApp
    branch: main
